[package]
name = "irc"
version = "0.1.0"
edition = "2024"

# [lints.clippy]
# unwrap_used = "deny"
# expect_used = "deny"
# panic = "deny"
#
# [lints.rust]
# unused_must_use = "deny"

[dependencies]
anyhow = "1"
dotenv = "0"
thiserror = "2"
